BEGIN
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'STORAGE',FALSE);
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'TABLESPACE',FALSE);
--DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'PCTSPACE',0);
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SEGMENT_ATTRIBUTES',FALSE);
--
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'CONSTRAINTS',TRUE);
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'REF_CONSTRAINTS',TRUE);
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'CONSTRAINTS_AS_ALTER',FALSE);
--
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SIZE_BYTE_KEYWORD',TRUE);
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SQLTERMINATOR',TRUE);
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'PRETTY',TRUE);
--
DBMS_METADATA.SET_REMAP_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'REMAP_SCHEMA','EXTDBA','A_REPIN');
------------------------------------------------------------------------------------------
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'STORAGE',FALSE);
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'TABLESPACE',FALSE);
--DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'PCTSPACE',0);
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SEGMENT_ATTRIBUTES',FALSE);
--
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'CONSTRAINTS',TRUE);
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'REF_CONSTRAINTS',TRUE);
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'CONSTRAINTS_AS_ALTER',FALSE);
--
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SIZE_BYTE_KEYWORD',TRUE);
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SQLTERMINATOR',TRUE);
DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'PRETTY',TRUE);
--
DBMS_METADATA.SET_REMAP_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'REMAP_SCHEMA','EXTDBA','A_REPIN');

END;
/
select DBMS_METADATA.GET_DDL('TABLE','EX$SEC_USER_LOC','EXTDBA') from DUAL; 
/
select DBMS_METADATA.GET_XML('TABLE','EX$SEC_ACCOUNT','EXTDBA') from DUAL; 

/
SELECT DBMS_METADATA.GET_DEPENDENT_DDL('REF_CONSTRAINT','<table_name>','<schema>') from dual;

/
SELECT * 
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'EXTDBA'
AND TABLE_NAME = 'EX$SEC_USER_LOC'
ORDER BY COLUMN_ID  ASC
/
SELECT 'CONSTRAINT ' 
    || CONSTRAINT_NAME 
    || CASE CONSTRAINT_TYPE
       WHEN 'C'
       THEN ' CHECK'
       WHEN 'P'
       THEN ' PRIMARY KEY'
       WHEN 'R'
       THEN ' FOREIGN KEY'
       ELSE ''
       END 
     ,SEARCH_CONDITION
FROM DBA_CONSTRAINTS
WHERE OWNER = 'EXTDBA'
AND TABLE_NAME = 'EX$SEC_USER_LOC'

/

DECLARE
LL LONG;
LC VARCHAR2(128);
BEGIN
LL := 'ksjdhka2311231fsd
asdasdasd
asda
sd
as
d
fsdfsdf2312312lkjl1k2j3l1k2j3l1k2j3l1k2j3l12kj3l12kj3l1k2j3l12kj3l12k3jl12kj3l12kj3l1k2j3l1k2j3l1k2j3l1k2j3l1k2j3l1k2j3jshkajshdkajshkajsdhkasjhd';
DBMS_OUTPUT.PUT_LINE(LL);
END;



/
SELECT * 
FROM DBA_INDEXES
WHERE TABLE_OWNER = 'EXTDBA'
AND TABLE_NAME = 'EX$SEC_USER_LOC'
/
SELECT * 
FROM DBA_TABLES
WHERE OWNER = 'EXTDBA'
AND TABLE_NAME = 'EX$SEC_USER_LOC'

/
select * FROM DBA_CONSTRAINTS
/
	 CONSTRAINT "EX$SCUSR_CCH01" CHECK (
            (BITAND(FLAGS,2) = 2 AND CREATED IS NOT NULL AND USER_CODE IS NOT NULL)
        OR  (BITAND(FLAGS,2) = 0 AND CREATED IS NULL AND USER_CODE IS  NULL)
        ) ENABLE, 
	 CONSTRAINT "EX$SCUSR_CCH02" CHECK (
             (BITAND(FLAGS,4) = 4 AND DELETED IS NOT NULL)
        OR  (BITAND(FLAGS,4)  = 0 AND DELETED IS NULL)

 ) ENABLE, 
	 CONSTRAINT "EX$SCUSR_CCH03" CHECK (
             (BITAND(FLAGS,8) = 8 AND LOCKDATE IS NOT NULL)
        OR    BITAND(FLAGS,8) = 0

 ) ENABLE, 
	 CONSTRAINT "EX$SCUSR_CCH04" CHECK (
             (BITAND(FLAGS,16) = 16 AND VALID_UNTIL IS NOT NULL)
        OR  BITAND(FLAGS,16) = 0

 ) ENABLE, 
	 CONSTRAINT "EX$SCUSR_CCH05" CHECK (
             (BITAND(FLAGS,32) = 32 AND PEXPIRY IS NOT NULL)
        OR  BITAND(FLAGS,32) = 0

 ) ENABLE, 
	 CONSTRAINT "EX$SCUSR_CCH06" CHECK (
             (BITAND(FLAGS,64) = 64 AND ACCOUNT_ID IS NOT NULL)
        OR  (BITAND(FLAGS,64) = 0 AND ACCOUNT_ID IS NULL)

 ) ENABLE, 
	 CONSTRAINT "EX$SCUSR_CCH07" CHECK ("CMASTER_UUID" IS NOT NULL AND "CHANGE_TSTAMP" IS NOT NULL OR "CMASTER_UUID" IS NULL AND "CHANGE_TSTAMP" IS NULL) ENABLE, 
	 CONSTRAINT "EX$SCUSR_CPK" PRIMARY KEY ("USER_ID") ENABLE, 
	 CONSTRAINT "EX$SEC_USER_LOC_CFK1" FOREIGN KEY ("CATALOG_UUID")
	  REFERENCES "EXTDBA"."EX$SEC_CATALOG" ("CATALOG_UUID") ENABLE, 
	 CONSTRAINT "EX$SEC_USER_LOC_CFK2" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "EXTDBA"."EX$SEC_ACCOUNT" ("ACCOUNT_ID") ENABLE
