Prompt drop TABLE BS$AG_MESSAGE_LOG;
DROP TABLE BS$AG_MESSAGE_LOG CASCADE CONSTRAINTS
/

Prompt Table BS$AG_MESSAGE_LOG;
--
-- BS$AG_MESSAGE_LOG  (Table) 
--
CREATE TABLE BS$AG_MESSAGE_LOG
(
  LOGSEQ        NUMBER CONSTRAINT EX$SCMSGL_CN01 NOT NULL,
  LOSTSTAMP     TIMESTAMP(6) CONSTRAINT EX$SCMSGL_CN02 NOT NULL,
  PROGRAM_NAME  VARCHAR2(48 BYTE),
  MODULE_NAME   VARCHAR2(64 BYTE),
  FUNC_NAME     VARCHAR2(64 BYTE),
  ACTION_NAME   VARCHAR2(128 BYTE),
  STEP_NAME     VARCHAR2(64 BYTE),
  MSG_HEADER    VARCHAR2(128 BYTE) CONSTRAINT EX$SCMSGL_CN04 NOT NULL,
  MSG_BODY      VARCHAR2(1024 BYTE),
  LFLAGS        BINARY_DOUBLE CONSTRAINT EX$SCMSGL_CN05 NOT NULL,
  FLAGS         BINARY_DOUBLE CONSTRAINT EX$SCMSGL_CN06 NOT NULL
)
TABLESPACE EXTDBA_NDC
LOGGING 
MONITORING
/

COMMENT ON TABLE BS$AG_MESSAGE_LOG IS 'Отладочные сообщения для расширения EX$_SEC'
/

COMMENT ON COLUMN BS$AG_MESSAGE_LOG.LOGSEQ IS 'ID записи отладки'
/

COMMENT ON COLUMN BS$AG_MESSAGE_LOG.LOSTSTAMP IS 'Время создания/вставки записи'
/

COMMENT ON COLUMN BS$AG_MESSAGE_LOG.PROGRAM_NAME IS 'Имя программы. Внутрянняя сущность EX$_SEC'
/

COMMENT ON COLUMN BS$AG_MESSAGE_LOG.MODULE_NAME IS 'Имя модуля.  Внутрянняя сущность EX$_SEC'
/

COMMENT ON COLUMN BS$AG_MESSAGE_LOG.FUNC_NAME IS 'Имя функции.  Внутрянняя сущность EX$_SEC'
/

COMMENT ON COLUMN BS$AG_MESSAGE_LOG.MSG_HEADER IS 'Заголовок сообщения'
/

COMMENT ON COLUMN BS$AG_MESSAGE_LOG.MSG_BODY IS 'Тело сообщения'
/

COMMENT ON COLUMN BS$AG_MESSAGE_LOG.LFLAGS IS 'Флаг урвня отладки'
/

COMMENT ON COLUMN BS$AG_MESSAGE_LOG.FLAGS IS 'Доп. аттрибуты'
/
