Prompt drop TABLE BS$AG_QUEUE_REG;
DROP TABLE BS$AG_QUEUE_REG CASCADE CONSTRAINTS
/

Prompt Table BS$AG_QUEUE_REG;
--
-- BS$AG_QUEUE_REG  (Table) 
--
CREATE TABLE BS$AG_QUEUE_REG
(
  REG_ID  NUMBER
)
TABLESPACE EXTDBA_NDC
LOGGING 
MONITORING
/
