Prompt drop TABLE BS$AG_EVENT_HANDLER;
DROP TABLE BS$AG_EVENT_HANDLER CASCADE CONSTRAINTS
/

Prompt Table BS$AG_EVENT_HANDLER;
--
-- BS$AG_EVENT_HANDLER  (Table) 
--
CREATE TABLE BS$AG_EVENT_HANDLER
(
  REG_ID  NUMBER
)
TABLESPACE EXTDBA_NDC
LOGGING 
MONITORING
/
