Prompt drop TABLE BS$AG_TASK_FLOW;
DROP TABLE BS$AG_TASK_FLOW CASCADE CONSTRAINTS
/

Prompt Table BS$AG_TASK_FLOW;
--
-- BS$AG_TASK_FLOW  (Table) 
--
CREATE TABLE BS$AG_TASK_FLOW
(
  TASK_ID  NUMBER
)
TABLESPACE EXTDBA_NDC
LOGGING 
MONITORING
/
