Prompt drop TABLE BS$AG_TASK_REG;
DROP TABLE BS$AG_TASK_REG CASCADE CONSTRAINTS
/

Prompt Table BS$AG_TASK_REG;
--
-- BS$AG_TASK_REG  (Table) 
--
CREATE TABLE BS$AG_TASK_REG
(
  REG_ID  NUMBER
)
TABLESPACE EXTDBA_NDC
LOGGING 
MONITORING
/
