Prompt drop TABLE BS$AG_TASK_QUEUE;
DROP TABLE BS$AG_TASK_QUEUE CASCADE CONSTRAINTS
/

Prompt Table BS$AG_TASK_QUEUE;
--
-- BS$AG_TASK_QUEUE  (Table) 
--
CREATE TABLE BS$AG_TASK_QUEUE
(
  TASK_ID  NUMBER
)
TABLESPACE EXTDBA_NDC
LOGGING 
MONITORING
/
