Prompt drop TABLE BS$AG_TASK_DATA;
DROP TABLE BS$AG_TASK_DATA CASCADE CONSTRAINTS
/

Prompt Table BS$AG_TASK_DATA;
--
-- BS$AG_TASK_DATA  (Table) 
--
CREATE TABLE BS$AG_TASK_DATA
(
  TASK_ID  NUMBER
)
TABLESPACE EXTDBA_NDC
LOGGING 
MONITORING
/
