Prompt drop View EX$_SEC_AG_USR_SFMAP;
DROP VIEW EX$_SEC_AG_USR_SFMAP
/

PROMPT View EX$_SEC_AG_USR_SFMAP;
--
-- EX$_SEC_AG_USR_SFMAP  (View)
--

CREATE OR REPLACE FORCE VIEW EX$_SEC_AG_USR_SFMAP
(
	SFLAGS
  ,SNAME
)
AS
	SELECT													 /* UNAME(EX$SEC V_1.2.0.0) */
			STATUS# AS SFLAGS, STATUS AS SNAME FROM sys.user_astatus_map
/
