Prompt drop TABLE EX$AG_SEC_CATALOG;
ALTER TABLE EX$AG_SEC_CATALOG
 DROP PRIMARY KEY CASCADE
/

DROP TABLE EX$AG_SEC_CATALOG CASCADE CONSTRAINTS
/

Prompt Table EX$AG_SEC_CATALOG;
--
-- EX$AG_SEC_CATALOG  (Table) 
--
CREATE TABLE EX$AG_SEC_CATALOG
(
  CAT_UUID            VARCHAR2(12 BYTE),
  CAT_SNAME           VARCHAR2(64 BYTE) CONSTRAINT EX$SCAGCAT_NN02 NOT NULL,
  FLAGS               BINARY_DOUBLE CONSTRAINT EX$SCAGCAT_NN03 NOT NULL,
  FLAGS_TSTAMP        TIMESTAMP(6) CONSTRAINT EX$SCAGCAT_NN04 NOT NULL,
  LAST_UPDATE_TSTAMP  TIMESTAMP(6) CONSTRAINT EX$SCAGCAT_NN05 NOT NULL,
  LAST_UPDATED_BY     NUMBER CONSTRAINT EX$SCAGCAT_NN06 NOT NULL,
  CREATION_TSTAMP     TIMESTAMP(6) CONSTRAINT EX$SCAGCAT_NN07 NOT NULL,
  CREATED_BY          NUMBER CONSTRAINT EX$SCAGCAT_NN08 NOT NULL
)
TABLESPACE EXTDBA_NDC
LOGGING 
MONITORING
/

COMMENT ON TABLE EX$AG_SEC_CATALOG IS 'Спиоск конфигурация агентов для данного каталога.'
/

COMMENT ON COLUMN EX$AG_SEC_CATALOG.CAT_UUID IS 'Глобальный идентификатор каталога, полученный при регистрации агента каталога'
/

COMMENT ON COLUMN EX$AG_SEC_CATALOG.CAT_SNAME IS 'Уникальное имя каталога, полученное при регистрации агента каталога'
/

COMMENT ON COLUMN EX$AG_SEC_CATALOG.FLAGS IS 'Флаги состояния для каталога:'
/

COMMENT ON COLUMN EX$AG_SEC_CATALOG.FLAGS_TSTAMP IS 'Время проверки флагов SFLAGS'
/

COMMENT ON COLUMN EX$AG_SEC_CATALOG.LAST_UPDATE_TSTAMP IS 'Аудит: Дата изменения записи'
/

COMMENT ON COLUMN EX$AG_SEC_CATALOG.LAST_UPDATED_BY IS 'Аудит: Кем изменена запись'
/

COMMENT ON COLUMN EX$AG_SEC_CATALOG.CREATION_TSTAMP IS 'Аудит: Дата создания записи'
/

COMMENT ON COLUMN EX$AG_SEC_CATALOG.CREATED_BY IS 'Аудит: Кем создана запись'
/


Prompt Index EX$SCAGCAT_UDX01;
--
-- EX$SCAGCAT_UDX01  (Index) 
--
CREATE UNIQUE INDEX EX$SCAGCAT_UDX01 ON EX$AG_SEC_CATALOG
(CAT_UUID)
LOGGING
TABLESPACE EXTDBA_NDC
/

Prompt Index EX$SCAGCAT_UDX02;
--
-- EX$SCAGCAT_UDX02  (Index) 
--
CREATE UNIQUE INDEX EX$SCAGCAT_UDX02 ON EX$AG_SEC_CATALOG
(CAT_SNAME)
LOGGING
TABLESPACE EXTDBA_NDC
/

-- 
-- Non Foreign Key Constraints for Table EX$AG_SEC_CATALOG 
-- 
Prompt Non-Foreign Key Constraints on Table EX$AG_SEC_CATALOG;
ALTER TABLE EX$AG_SEC_CATALOG ADD (
  CONSTRAINT EX$SCAGCAT_CPK01
  PRIMARY KEY
  (CAT_UUID)
  USING INDEX EX$SCAGCAT_UDX01
  ENABLE VALIDATE)
/

ALTER TABLE EX$AG_SEC_CATALOG ADD (
  CONSTRAINT EX$SCAGCAT_CUQ1
  UNIQUE (CAT_SNAME)
  USING INDEX EX$SCAGCAT_UDX02
  ENABLE VALIDATE)
/

ALTER TABLE EX$AG_SEC_CATALOG_CFG ADD (
  CONSTRAINT EX$SCAGCFG_CFK01 
  FOREIGN KEY (CAT_UUID) 
  REFERENCES EX$AG_SEC_CATALOG (CAT_UUID))
/
