Prompt drop TABLE EX$AG_SEC_AUD_BUFF_OPS_OPMAP;
ALTER TABLE EX$AG_SEC_AUD_BUFF_OPS_OPMAP
 DROP PRIMARY KEY CASCADE
/

DROP TABLE EX$AG_SEC_AUD_BUFF_OPS_OPMAP CASCADE CONSTRAINTS
/

Prompt Table EX$AG_SEC_AUD_BUFF_OPS_OPMAP;
--
-- EX$AG_SEC_AUD_BUFF_OPS_OPMAP  (Table) 
--
CREATE TABLE EX$AG_SEC_AUD_BUFF_OPS_OPMAP
(
  OPCODE  BINARY_DOUBLE,
  OPNAME  VARCHAR2(128 BYTE)
)
TABLESPACE EXTDBA_NDC
LOGGING 
MONITORING
/

COMMENT ON TABLE EX$AG_SEC_AUD_BUFF_OPS_OPMAP IS 'Справочник кодов операций для EX$_SEC_AUD_BUFF_OPS'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_BUFF_OPS_OPMAP.OPCODE IS 'Флаги кода операции'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_BUFF_OPS_OPMAP.OPNAME IS 'Название операции'
/


Prompt Index EX$SCAUDBOPM_UDX01;
--
-- EX$SCAUDBOPM_UDX01  (Index) 
--
CREATE UNIQUE INDEX EX$SCAUDBOPM_UDX01 ON EX$AG_SEC_AUD_BUFF_OPS_OPMAP
(OPCODE)
LOGGING
TABLESPACE EXTDBA_NDC
/

-- 
-- Non Foreign Key Constraints for Table EX$AG_SEC_AUD_BUFF_OPS_OPMAP 
-- 
Prompt Non-Foreign Key Constraints on Table EX$AG_SEC_AUD_BUFF_OPS_OPMAP;
ALTER TABLE EX$AG_SEC_AUD_BUFF_OPS_OPMAP ADD (
  CONSTRAINT EX$SCAUDBOPM_CPK
  PRIMARY KEY
  (OPCODE)
  USING INDEX EX$SCAUDBOPM_UDX01
  ENABLE VALIDATE)
/

ALTER TABLE EX$AG_SEC_AUD_BUFF_OPS ADD (
  CONSTRAINT EX$SCAUDBO_CFK05 
  FOREIGN KEY (OPCODE) 
  REFERENCES EX$AG_SEC_AUD_BUFF_OPS_OPMAP (OPCODE))
/
