Prompt drop TABLE EX$AG_SEC_CATALOG_CFG;
DROP TABLE EX$AG_SEC_CATALOG_CFG CASCADE CONSTRAINTS
/

Prompt Table EX$AG_SEC_CATALOG_CFG;
--
-- EX$AG_SEC_CATALOG_CFG  (Table) 
--
CREATE TABLE EX$AG_SEC_CATALOG_CFG
(
  CAT_UUID            VARCHAR2(12 BYTE) CONSTRAINT EX$SCAGCFG_NN01 NOT NULL,
  CFLAGS              BINARY_DOUBLE CONSTRAINT EX$SCAGCFG_NN02 NOT NULL,
  CSPACE              VARCHAR2(64 BYTE) CONSTRAINT EX$SCAGCFG_NN03 NOT NULL,
  CBODY               SYS.XMLTYPE CONSTRAINT EX$SCAGCFG_NN04 NOT NULL,
  LAST_UPDATE_TSTAMP  TIMESTAMP(6) CONSTRAINT EX$SCAGCFG_NN05 NOT NULL,
  LAST_UPDATED_BY     NUMBER CONSTRAINT EX$SCAGCFG_NN06 NOT NULL,
  CREATION_TSTAMP     TIMESTAMP(6) CONSTRAINT EX$SCAGCFG_NN07 NOT NULL,
  CREATED_BY          NUMBER CONSTRAINT EX$SCAGCFG_NN08 NOT NULL
)
XMLTYPE CBODY STORE AS CLOB (
  TABLESPACE  EXTDBA_NDC
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  PCTVERSION  10
  LOGGING
      STORAGE    (
                  INITIAL          8M
                  NEXT             8M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
TABLESPACE EXTDBA_NDC
LOGGING 
MONITORING
/


-- 
-- Foreign Key Constraints for Table EX$AG_SEC_CATALOG_CFG 
-- 
Prompt Foreign Key Constraints on Table EX$AG_SEC_CATALOG_CFG;
ALTER TABLE EX$AG_SEC_CATALOG_CFG ADD (
  CONSTRAINT EX$SCAGCFG_CFK01 
  FOREIGN KEY (CAT_UUID) 
  REFERENCES EX$AG_SEC_CATALOG (CAT_UUID)
  ENABLE VALIDATE)
/
