Prompt drop TABLE EX$AG_SEC_AUD_SESS_ERRORS;
DROP TABLE EX$AG_SEC_AUD_SESS_ERRORS CASCADE CONSTRAINTS
/

Prompt Table EX$AG_SEC_AUD_SESS_ERRORS;
--
-- EX$AG_SEC_AUD_SESS_ERRORS  (Table) 
--
CREATE TABLE EX$AG_SEC_AUD_SESS_ERRORS
(
  GROUP#      NUMBER(2) CONSTRAINT EX$SCAUDBERR_CNN01 NOT NULL,
  OPS_UID     NUMBER CONSTRAINT EX$SCAUDBERR_CNN02 NOT NULL,
  LOGON_TIME  DATE CONSTRAINT EX$SCAUDBERR_CNN03 NOT NULL,
  AUDTSTAMP   TIMESTAMP(3) CONSTRAINT EX$SCAUDBERR_CNN04 NOT NULL,
  USER_NAME   VARCHAR2(64 BYTE) CONSTRAINT EX$SCAUDBERR_CNN05 NOT NULL,
  USER_CODE   NUMBER CONSTRAINT EX$SCAUDBERR_CNN06 NOT NULL,
  OSUSER      VARCHAR2(128 BYTE) CONSTRAINT EX$SCAUDBERR_CNN07 NOT NULL,
  SFLAGS      BINARY_DOUBLE CONSTRAINT EX$SCAUDBERR_CNN08 NOT NULL,
  FLAGS       BINARY_DOUBLE,
  ERR_CODE    NUMBER,
  ERR_MSG     VARCHAR2(2000 BYTE),
  FAIL_NUM    NUMBER
)
TABLESPACE EXTDBA_NDC
LOGGING 
COMPRESS 
MONITORING
/

COMMENT ON TABLE EX$AG_SEC_AUD_SESS_ERRORS IS 'ссылки на ошибочные строки, которые не удалось перенести из буффера в журнал аудита сессий'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_ERRORS.GROUP# IS 'Номер группы'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_ERRORS.OPS_UID IS 'ID операции'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_ERRORS.LOGON_TIME IS 'Время создания сессии'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_ERRORS.AUDTSTAMP IS 'Время создания записи в журнале'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_ERRORS.USER_NAME IS 'Уч. система:Имя пользователя'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_ERRORS.USER_CODE IS 'Уч. система:Код пользователя'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_ERRORS.OSUSER IS 'Уч. система:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_ERRORS.SFLAGS IS 'Флаги состояни записи'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_ERRORS.FLAGS IS 'Доп.аттрибуты записи'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_ERRORS.ERR_CODE IS 'Последний код ошибки. По которой не удалось перенести запись'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_ERRORS.ERR_MSG IS 'Последнее сообщение ошибки. По которой не удалось перенести запись'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_ERRORS.FAIL_NUM IS 'Кол-во попыток переноса на данный момент'
/


-- 
-- Foreign Key Constraints for Table EX$AG_SEC_AUD_SESS_ERRORS 
-- 
Prompt Foreign Key Constraints on Table EX$AG_SEC_AUD_SESS_ERRORS;
ALTER TABLE EX$AG_SEC_AUD_SESS_ERRORS ADD (
  CONSTRAINT EX$SCAUDBERR_CFK01 
  FOREIGN KEY (OPS_UID) 
  REFERENCES EX$AG_SEC_AUD_BUFF_OPS (OUID)
  ENABLE VALIDATE)
/
