Prompt drop TABLE EX$AG_SEC_AUD_SESS_LOG_LOC;
DROP TABLE EX$AG_SEC_AUD_SESS_LOG_LOC CASCADE CONSTRAINTS
/

Prompt Table EX$AG_SEC_AUD_SESS_LOG_LOC;
--
-- EX$AG_SEC_AUD_SESS_LOG_LOC  (Table) 
--
CREATE TABLE EX$AG_SEC_AUD_SESS_LOG_LOC
(
  LOGON_TIME         DATE,
  AUDSEQ             NUMBER,
  AUDTSTAMP          TIMESTAMP(3),
  SFLAGS             BINARY_DOUBLE,
  FLAGS              BINARY_DOUBLE,
  CAT_UUID           VARCHAR2(12 BYTE),
  USER_NAME          VARCHAR2(64 BYTE),
  USER_CODE          NUMBER,
  OSUSER             VARCHAR2(128 BYTE),
  CLIENT_HOST        VARCHAR2(128 BYTE),
  CLIENT_IP          VARCHAR2(64 BYTE),
  TERMINAL           VARCHAR2(128 BYTE),
  PROGRAM_SNAME      VARCHAR2(128 BYTE),
  MODULE_SNAME       VARCHAR2(128 BYTE),
  ACTION             VARCHAR2(128 BYTE),
  CLIENT_INFO        VARCHAR2(128 BYTE),
  CLIENT_IDENTIFIER  VARCHAR2(128 BYTE),
  SERVER_HOST        VARCHAR2(128 BYTE),
  SESS_ID            NUMBER,
  SESS_SERIAL#       NUMBER,
  SESS_AUDSID        NUMBER,
  SESS_SPID          VARCHAR2(12 BYTE),
  SERVICE_NAME       VARCHAR2(64 BYTE),
  DB_UNIQUE_NAME     VARCHAR2(64 BYTE),
  AUD_LOGON_CODE     NUMBER,
  AUDIT_LOGON_MSG    VARCHAR2(128 BYTE),
  SQL_TRACE          CHAR(1 BYTE),
  SQL_TRACE_WAITS    CHAR(1 BYTE),
  SQL_TRACE_BINDS    CHAR(1 BYTE),
  PROXY_USER         VARCHAR2(64 BYTE),
  PROXY_USERID       NUMBER,
  ISDBA              CHAR(1 BYTE),
  FG_JOB_ID          NUMBER,
  DB_NAME            VARCHAR2(64 BYTE),
  DB_DOMAIN          VARCHAR2(64 BYTE),
  BG_JOB_ID          NUMBER,
  SESS_ATTRIBUTE01   VARCHAR2(128 BYTE),
  SESS_ATTRIBUTE02   VARCHAR2(128 BYTE),
  SESS_ATTRIBUTE03   VARCHAR2(128 BYTE),
  SESS_ATTRIBUTE04   VARCHAR2(128 BYTE),
  SESS_ATTRIBUTE05   VARCHAR2(128 BYTE),
  SESS_ATTRIBUTE06   NUMBER,
  SESS_ATTRIBUTE07   NUMBER,
  SESS_ATTRIBUTE08   NUMBER,
  SESS_ATTRIBUTE09   DATE,
  SESS_ATTRIBUTE10   DATE
)
TABLESPACE EXTDBA_NDC
LOGGING 
COMPRESS 
MONITORING
/

COMMENT ON TABLE EX$AG_SEC_AUD_SESS_LOG_LOC IS 'Аудит сессий в учетных системах. Журнальная таблица. Глоб.репозитария'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.LOGON_TIME IS 'Время создания сессии'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.AUDSEQ IS 'Номер записи аудита из последовательности'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.AUDTSTAMP IS 'Время записи аудита'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SFLAGS IS 'Флаги состония записи'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.FLAGS IS 'Флаги доп.аттрибутов'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.CAT_UUID IS 'Идентификатор каталога учетных записей'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.USER_NAME IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.USER_CODE IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.OSUSER IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.CLIENT_HOST IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.CLIENT_IP IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.TERMINAL IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.PROGRAM_SNAME IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.MODULE_SNAME IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.ACTION IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.CLIENT_INFO IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.CLIENT_IDENTIFIER IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SERVER_HOST IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_ID IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_SERIAL# IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_AUDSID IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_SPID IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SERVICE_NAME IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.DB_UNIQUE_NAME IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.AUD_LOGON_CODE IS 'Код возврата при входе. Если > 0 вход был запрещен'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.AUDIT_LOGON_MSG IS 'Сообщение пользователю при входе. Если поле не пустое вход был запрещен'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SQL_TRACE IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SQL_TRACE_WAITS IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SQL_TRACE_BINDS IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.PROXY_USER IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.PROXY_USERID IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.ISDBA IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.FG_JOB_ID IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.DB_NAME IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.DB_DOMAIN IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.BG_JOB_ID IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_ATTRIBUTE01 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_ATTRIBUTE02 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_ATTRIBUTE03 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_ATTRIBUTE04 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_ATTRIBUTE05 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_ATTRIBUTE06 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_ATTRIBUTE07 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_ATTRIBUTE08 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_ATTRIBUTE09 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_LOG_LOC.SESS_ATTRIBUTE10 IS 'Доплнительносе поле для использования в будущем.'
/
