Prompt drop TABLE EX$AG_SEC_AUD_SESS_BUFF;
DROP TABLE EX$AG_SEC_AUD_SESS_BUFF CASCADE CONSTRAINTS
/

Prompt Table EX$AG_SEC_AUD_SESS_BUFF;
--
-- EX$AG_SEC_AUD_SESS_BUFF  (Table) 
--
CREATE TABLE EX$AG_SEC_AUD_SESS_BUFF
(
  GROUP#             NUMBER(2),
  LOGON_TIME         DATE,
  AUDSEQ             NUMBER,
  AUDTSTAMP          TIMESTAMP(3),
  SFLAGS             BINARY_DOUBLE,
  FLAGS              BINARY_DOUBLE,
  CAT_UUID           VARCHAR2(12 BYTE),
  USER_NAME          VARCHAR2(64 BYTE),
  USER_CODE          NUMBER,
  OSUSER             VARCHAR2(128 BYTE),
  CLIENT_HOST        VARCHAR2(128 BYTE),
  CLIENT_IP          VARCHAR2(64 BYTE),
  TERMINAL           VARCHAR2(128 BYTE),
  PROGRAM_SNAME      VARCHAR2(128 BYTE),
  MODULE_SNAME       VARCHAR2(128 BYTE),
  ACTION             VARCHAR2(128 BYTE),
  CLIENT_INFO        VARCHAR2(128 BYTE),
  CLIENT_IDENTIFIER  VARCHAR2(128 BYTE),
  SERVER_HOST        VARCHAR2(128 BYTE),
  SESS_ID            NUMBER,
  SESS_SERIAL#       NUMBER,
  SESS_AUDSID        NUMBER,
  SESS_SPID          VARCHAR2(12 BYTE),
  SERVICE_NAME       VARCHAR2(64 BYTE),
  DB_UNIQUE_NAME     VARCHAR2(64 BYTE),
  AUD_LOGON_CODE     NUMBER,
  AUDIT_LOGON_MSG    VARCHAR2(128 BYTE),
  SQL_TRACE          CHAR(1 BYTE),
  SQL_TRACE_WAITS    CHAR(1 BYTE),
  SQL_TRACE_BINDS    CHAR(1 BYTE),
  PROXY_USER         VARCHAR2(64 BYTE),
  PROXY_USERID       NUMBER,
  ISDBA              CHAR(1 BYTE),
  FG_JOB_ID          NUMBER,
  DB_NAME            VARCHAR2(64 BYTE),
  DB_DOMAIN          VARCHAR2(64 BYTE),
  BG_JOB_ID          NUMBER,
  SESS_ATTRIBUTE01   VARCHAR2(128 BYTE),
  SESS_ATTRIBUTE02   VARCHAR2(128 BYTE),
  SESS_ATTRIBUTE03   VARCHAR2(128 BYTE),
  SESS_ATTRIBUTE04   VARCHAR2(128 BYTE),
  SESS_ATTRIBUTE05   VARCHAR2(128 BYTE),
  SESS_ATTRIBUTE06   NUMBER,
  SESS_ATTRIBUTE07   NUMBER,
  SESS_ATTRIBUTE08   NUMBER,
  SESS_ATTRIBUTE09   DATE,
  SESS_ATTRIBUTE10   DATE
)
COMPRESS 
TABLESPACE EXTDBA_NDC
PARTITION BY LIST (GROUP#)
(  
  PARTITION EX$SCUSRLBUFF_PG01 VALUES (1)
    LOGGING
    COMPRESS 
    TABLESPACE EXTDBA_NDC,  
  PARTITION EX$SCUSRLBUFF_PG02 VALUES (2)
    LOGGING
    COMPRESS 
    TABLESPACE EXTDBA_NDC,  
  PARTITION EX$SCUSRLBUFF_PG03 VALUES (3)
    LOGGING
    COMPRESS 
    TABLESPACE EXTDBA_NDC,  
  PARTITION EX$SCUSRLBUFF_PG04 VALUES (4)
    LOGGING
    COMPRESS 
    TABLESPACE EXTDBA_NDC,  
  PARTITION EX$SCUSRLBUFF_PG05 VALUES (5)
    LOGGING
    COMPRESS 
    TABLESPACE EXTDBA_NDC
)
MONITORING
/

COMMENT ON TABLE EX$AG_SEC_AUD_SESS_BUFF IS 'Аудит сессий в учетных системах. Буфферая таблица'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.GROUP# IS 'Номер группы буфера'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.LOGON_TIME IS 'Время создания сессии'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.AUDSEQ IS 'Номер записи аудита из последовательности'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.AUDTSTAMP IS 'Время записи аудита'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SFLAGS IS 'Флаги состония записи'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.FLAGS IS 'Флаги доп.аттрибутов'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.CAT_UUID IS 'Идентификатор каталога учетных записей'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.USER_NAME IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.USER_CODE IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.OSUSER IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.CLIENT_HOST IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.CLIENT_IP IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.TERMINAL IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.PROGRAM_SNAME IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.MODULE_SNAME IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.ACTION IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.CLIENT_INFO IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.CLIENT_IDENTIFIER IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SERVER_HOST IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_ID IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_SERIAL# IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_AUDSID IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_SPID IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SERVICE_NAME IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.DB_UNIQUE_NAME IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.AUD_LOGON_CODE IS 'Код возврата при входе. Если > 0 вход был запрещен'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.AUDIT_LOGON_MSG IS 'Сообщение пользователю при входе. Если поле не пустое вход был запрещен'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SQL_TRACE IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SQL_TRACE_WAITS IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SQL_TRACE_BINDS IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.PROXY_USER IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.PROXY_USERID IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.ISDBA IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.FG_JOB_ID IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.DB_NAME IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.DB_DOMAIN IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.BG_JOB_ID IS 'Уч.сист.:'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_ATTRIBUTE01 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_ATTRIBUTE02 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_ATTRIBUTE03 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_ATTRIBUTE04 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_ATTRIBUTE05 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_ATTRIBUTE06 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_ATTRIBUTE07 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_ATTRIBUTE08 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_ATTRIBUTE09 IS 'Доплнительносе поле для использования в будущем.'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_SESS_BUFF.SESS_ATTRIBUTE10 IS 'Доплнительносе поле для использования в будущем.'
/
