Prompt drop Sequence EX$AGSCAUDSEQ_S;
DROP SEQUENCE EX$AGSCAUDSEQ_S
/

Prompt Sequence EX$AGSCAUDSEQ_S;
--
-- EX$AGSCAUDSEQ_S  (Sequence) 
--
CREATE SEQUENCE EX$AGSCAUDSEQ_S
  START WITH 1
  MAXVALUE 9999999999999
  MINVALUE 1
  CYCLE
  NOCACHE
  NOORDER
/
