Prompt drop TABLE EX$AG_SEC_AUD_BUFF_CURR;
DROP TABLE EX$AG_SEC_AUD_BUFF_CURR CASCADE CONSTRAINTS
/

Prompt Table EX$AG_SEC_AUD_BUFF_CURR;
--
-- EX$AG_SEC_AUD_BUFF_CURR  (Table) 
--
CREATE TABLE EX$AG_SEC_AUD_BUFF_CURR
(
  TP#     NUMBER(2) CONSTRAINT EX$SCABGC_CNN01  NOT NULL,
  GROUP#  NUMBER(2) CONSTRAINT EX$SCABGC_CNN02  NOT NULL,
  CURREF  NUMBER,
  SFLAGS  BINARY_DOUBLE CONSTRAINT EX$SCABGC_CNN03 NOT NULL,
  SPARE#  NUMBER,
  PNAME   VARCHAR2(64 BYTE) CONSTRAINT EX$SCABGC_CNN04 NOT NULL,
  LNAME   VARCHAR2(64 BYTE)
)
TABLESPACE EXTDBA_NDC
LOGGING 
MONITORING
/

COMMENT ON TABLE EX$AG_SEC_AUD_BUFF_CURR IS 'Доп. таблица для буфферных групп аудита. Используется пользовательскыми сессиями. Создана для снижения нагрузки на основную таблицу список буфферных групп'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_BUFF_CURR.TP# IS 'Внешний ключ. Тип буфферной группы'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_BUFF_CURR.GROUP# IS 'Внешний ключ. Номер буфферной группы'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_BUFF_CURR.CURREF IS 'Внешний ключ. Ссылка CURRENT (активную) буфферную группу. Обеспечивает целостность данных'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_BUFF_CURR.SFLAGS IS 'Флаги состояния. (16)x4 - Группа активна (CURRENT)'
/

COMMENT ON COLUMN EX$AG_SEC_AUD_BUFF_CURR.SPARE# IS 'Резервная группа. При "поломке" текущей активной.'
/


Prompt Index EX$SCABGC_UDX01;
--
-- EX$SCABGC_UDX01  (Index) 
--
CREATE UNIQUE INDEX EX$SCABGC_UDX01 ON EX$AG_SEC_AUD_BUFF_CURR
(TP#, GROUP#)
LOGGING
TABLESPACE EXTDBA_NDC
/

-- 
-- Non Foreign Key Constraints for Table EX$AG_SEC_AUD_BUFF_CURR 
-- 
Prompt Non-Foreign Key Constraints on Table EX$AG_SEC_AUD_BUFF_CURR;
ALTER TABLE EX$AG_SEC_AUD_BUFF_CURR ADD (
  CONSTRAINT EX$SCABGC_CCH01
  CHECK (
         (BITAND("SFLAGS",16) = 16 AND CURREF IS NOT NULL )
      OR (BITAND("SFLAGS",16)!= 16 AND CURREF IS  NULL )
         )
  ENABLE VALIDATE)
/

ALTER TABLE EX$AG_SEC_AUD_BUFF_CURR ADD (
  CONSTRAINT EX$SCABGC_CUQ01
  UNIQUE (TP#, GROUP#)
  USING INDEX EX$SCABGC_UDX01
  ENABLE VALIDATE)
/


-- 
-- Foreign Key Constraints for Table EX$AG_SEC_AUD_BUFF_CURR 
-- 
Prompt Foreign Key Constraints on Table EX$AG_SEC_AUD_BUFF_CURR;
ALTER TABLE EX$AG_SEC_AUD_BUFF_CURR ADD (
  CONSTRAINT EX$SCABGC_CFK01 
  FOREIGN KEY (TP#, GROUP#, CURREF) 
  REFERENCES EX$AG_SEC_AUD_BUFF_GRP (TP#,GROUP#,CURREF)
  ENABLE VALIDATE)
/
